# Micropython code
from machine import Pin, ADC

BUZZER_PIN = 2
LCD_SDA_PIN = 3
LCD_SCL_PIN = 4
RTC_RST_PIN = 5
RTC_DAT_PIN = 6
RTC_CLK_PIN = 7
RFID_READER_SDA_PIN = 12
RFID_READER_SCK_PIN = 13
RFID_READER_MOSI_PIN = 16
RFID_READER_MISO_PIN = 17
RFID_READER_RST_PIN = 21
LED_B_PIN = 18
LED_G_PIN = 19
LED_R_PIN = 20